--[[
	Install script generated by rbxpacker {{VERSION}}.
]]

local source = [=[{{SOURCE}}]=]

local decoded = game:GetService("HttpService"):JSONDecode(source)
local root = game:GetService("Selection"):Get()[1]

if not root then
	print(" \n  \n\tPlease select an object in Explorer to install into.\n \n")
	return
end

local function makeLeaf(name, contents)
	local basename, extension = name:match("^(.*)%.(.-)$")

	if extension == "lua" then
		local created = Instance.new("ModuleScript")
		created.Name = basename
		created.Source = contents

		return created
	else
		local created = Instance.new("StringValue")
		created.Name = basename
		created.Value = contents

		return created
	end
end

local function import(root, path, contents)
	local location = root

	for key, piece in ipairs(path) do
		local newLocation = location:FindFirstChild(piece)

		if not newLocation then
			local instance
			if key == #path then
				instance = makeLeaf(piece, contents)
			else
				instance = Instance.new("Folder")
				instance.Name = piece
			end

			instance.Parent = location
			newLocation = instance
		end

		location = newLocation
	end

	return location
end

for _, file in ipairs(decoded.files) do
	import(root, file.path, file.contents)
end